class Html{
    constructor() {

        this.body = 
       `<!DOCTYPE html>
        <html>
        
        <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <title>Team Profile</title>
            <meta name="description" content="">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link rel="stylesheet" href="">
        </head>
        
        <body>
            <div class="text-white bg-dark pt-4 pb-4">
                <div class="text-center">
                    <h1 class="">Team Profile</h1>
                </div>
            </div>
            <div class="container">
                <div class="row pt-5">`;

        this.foot = 
               `</div>
            </div>
        </div>
        <footer>
            <div class="footer-copyright text-center py-3">This webpage was generated by
                <a href="https://github.com/TRemigi/Team-Profile-Generator">The Team Profile Generator ©</a>
            </div>
        </footer>

    </body>

    </html>`;
    }

    createEmployeeCard = function(element) {
        let html = 
                       `<div class="col-12 col-md-6 col-lg-4">
                            <div class="card">
                                <div class="card-header text-white bg-dark mb-3">
                                    <h2>${element.name}</h2>
                                    <h4>${element.role}<span>icon</span></h4>
                                </div>
                                    <div class="card-body font-weight-bold">
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">ID: ${element.id}</li>
                                            <li class="list-group-item">Email: <a href="${element.email}">${element.email}</a>
                                            </li>
                                            <li class="list-group-item">${element.roleInfoType}:
                                                ${element.roleInfo}
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>`
        return html;
    }

}


module.exports = Html;